runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
env_variables:
  YOUTUBE_API_KEY: 'yourkey'